spring:
  jackson:
    default-property-inclusion: non_null

data:
   satellite:
    - 
      name: kenobi
      position-x: -500
      position-y: -200
    -
      name: skywalker
      position-x: 100.0
      position-y: -100.0
    - 
      name: sato
      position-x: 500.0
      position-y: 100.0
